os: 
    - linux
    - osx

arch: amd64
language: generic
cache:
    apt: true
    directories:
        - "$HOME/.stack/"
        - "$HOME/.local/bin/"
        - ".stack-work/"

addons:
    apt:
        update: true
        packages:
            - imagemagick
            - gcc
    homebrew:
        update: true
        packages:
            - imagemagick
            - gcc

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - ./.travis/install-stack.sh

install:
    - stack --no-terminal test --only-dependencies

jobs:
    include:
        - stage: Run build on Linux
          os: linux
          script: stack build
        
        - stage: Run build on macOS
          os: osx
          script: stack build --ghc-options="-optP-Wno-nonportable-include-path"
        
        - stage: Run compiler test
          os: linux
          script: 
            - stack test
            - stack test --test-arguments subp
              
        - stage: Run compiling and executing example C codes
          os: linux
          script:
            - cd example && make && cd dist && ./knapsack && ./merge_sorting_linked_list && ./shuffle_and_sort
        
        - stage: Run generating AST graphs on Linux
          os: linux
          script:
            - ./travis/visualize-test.sh
        
        - stage: Run generating AST graphs on macOS
          os: osx
          script:
            - ./travis/visualize-test.sh
        
        - stage: Run compiler test on Docker
          os: linux
          services: docker
          script:
              - stack test --test-arguments docker
              - stack test --test-arguments cleanDocker

        - stage: Run compiling and executing example C codes on Docker
          os: linux
          services: docker
          script:
              - cd example && make docker && make clean_docker

notifications:
    email: false
