build: off

platform: Any CPU

before_test:
    - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
    - curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
    - 7z x stack.zip stack.exe

clone_folder: "c:\\stack"

environment:
    global:
        STACK_ROOT: "c:\\sr"
        TMP: "c:\\tmp"

    matrix:
        - ARGS: ""
        - ARGS: "--test-arguments docker"

test_script:
    - stack setup > nul
    - chcp 65001
    - echo "" | stack --no-terminal test --only-dependencies
    - echo "" | stack test %ARGS%
    - echo "" | stack test --test-arguments cleanDocker
