build: off

platform: Any CPU

before_test:
    - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
    - curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
    - 7z x stack.zip stack.exe
    - chcp 65001

clone_folder: "c:\\stack"

environment:
    global:
        STACK_ROOT: "c:\\sr"
        TMP: "c:\\tmp"

test_script:
    - stack setup > nul
    - echo "" | stack --no-terminal test
    - echo "" | stack test --no-terminal --test-arguments docker
    - echo "" | stack test --no-terminal --test-arguments cleanDocker
