name:                htcc
version:             0.0.0.1
synopsis:            The full scratch implementation of tiny C compiler (x86_64)
description: |
    The full scratch implementation of tiny C compiler (x86_64).
    This compiler outputs x86_64 assembly code from "general" C code.
    .
    It consists of:
    .
    * the lexical analyzer
    * the parser that performs parsing with recursive descent and construction of abstract syntax trees (ASTs)
    * the method that outputs x86_64 assembly code from ASTs
    .
    __This compiler is not practical purposes__, but focuses on implementation experiments.
    .
    For more information, please see the README on GitHub at <https://github.com/falgon/htcc#readme>.
category:            Compiler
github:              "falgon/htcc"
license:             MIT
author:              "roki"
maintainer:          "falgon53@yahoo.co.jp"
copyright:           "2019 roki"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- ansi-wl-pprint
- cond
- extra
- text
- split
- monad-loops
- containers
- bytestring
- deepseq
- safe
- mtl
- monad-finally
- mono-traversable
- transformers
- diagrams-svg
- diagrams-contrib
- diagrams-lib
- natural-transformation

library:
  source-dirs: src

executables:
  htcc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -O2
    dependencies:
    - htcc
    - directory
    - optparse-applicative

tests:
  htcc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - htcc
    - HUnit
    - turtle
    - text
    - directory
    - time
    - foldl
    - hspec
    - hspec-core
    - hspec-contrib

benchmarks:
    criterion:
        main: bench/Criterion.hs
        ghc-options:
        - -O2
        dependencies:
        - criterion
        - htcc
