name:                htcc
version:             0.0.0.1
github:              "falgon/htcc"
license:             MIT
author:              "roki"
maintainer:          "falgon53@yahoo.co.jp"
copyright:           "2019 roki"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/falgon/htcc#readme>

dependencies:
- base >= 4.7 && < 5
- extra

library:
  source-dirs: src

executables:
  htcc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - htcc
    - extra

tests:
  htcc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -O2
    dependencies:
    - htcc
    - HUnit
    - turtle
    - text
    - directory
    - time
