version: '3'
services:
    htcc:
        image: roki/htcc_example:1.0.0
        command: /bin/sh -c 'gcc -no-pie -o spec /htcc_work/spec.s && ./spec'
        volumes:
            - /tmp/htcc:/htcc_work
        build:
            context: .
            dockerfile: Dockerfile
